version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./backend-api/data:/data
      - ./mongodb-data:/docker-entrypoint-initdb.d

    working_dir: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
    networks:
      - app-network

  backend-api:
    build: ./backend-api
    container_name: backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend-api:/app
    working_dir: /app
    networks:
      - app-network
    depends_on:
      - mongo

  flutter-dev:
    build: .
    container_name: flutter-dev
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /app
    networks:
      - app-network
    depends_on:
      - backend-api

networks:
  app-network:
    driver: bridge

